[package]
authors = ["Zelda Hessler <zelda.hessler@pm.me>"]
description = "A library for divination with the I-Ching"
edition = "2018"
license = "MIT/Apache-2.0"
name = "iching"
repository = "https://github.com/Velfi/i-ching"
version = "0.1.0"

[lib]
name = "iching"
path = "src/lib.rs"

[[bin]]
name = "iching"
path = "src/bin/main.rs"

[dependencies]
clap = "2.32"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
