[package]
name = "iching"
version = "0.1.0"
authors = ["Zelda Hessler <zelda.hessler@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
